### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dem10** [Telariust/pollard-kangaroo#1]
[+] T1+W1 herds - ready
[i] DP T1+W1=3+3=6; dp/kgr=3.0
Traceback (most recent call last):
  File "pollard-kangaroo.py", line 884, in <module>
    prvkey, runjump, runtime, lenT,lenW, HTmax,HWmax, nTrepair,nWrepair = KANGAROOS()
  File "pollard-kangaroo.py", line 547, in KANGAROOS
    timeleft = (t2-t0)*(1-(n_jump/(2*Wsqrt)))/(n_jump/(2*Wsqrt))
ZeroDivisionError: float division by zero

**Comment by Telariust** [comment]
u right, i see
python2 only, int/int=int, but need float result
simple fix as add 1.0* 
`timeleft = (t2-t0)(1-(1.0*n_jump/(2*Wsqrt)))/(1.0*n_jump/(2*Wsqrt))`
will be fixed in new release
