### ISSUE TITLE
multiple pubkeys in bit range at once checker

### ISSUE THREAD

**Issue by hamnaz** [Telariust/pollard-kangaroo#3]
multiple publickeys could be check ....
update your script with multiple public keys to check in bit range
could be inside script or could be pick from publickeys.txt file
.....

**Comment by Telariust** [comment]
For sequentially calculation, you can already do this using bat/sh script by restarting with a new custom pubkey.

for windows
_run.bat 
```
@Echo Off
COLOR 0A

SET file=PublicKey0001.txt

setlocal enabledelayedexpansion

SET sessFile=_session.txt

SET Npubkey=0
echo [~] calc total Npubkey in file "!file!" ..
For /F %%a In (%file%) Do (
	SET /a Npubkey+=1
)

SET lastN=0
IF EXIST !sessFile! (
	SET /P lastN=<!sessFile!
)

SET n=0
For /F %%a In (%file%) Do (
	echo =================================================
	REM date /T && time /T
	powershell Get-Date
	echo [!n!/!Npubkey!] %%a

	IF !lastN! == !n! (
		echo !n!>!sessFile!

		C:\Python37\python.exe pollard-kangaroo.py 32 %%a
		REM timeout /T 1

		SET /a lastN+=1
	)

	SET /a n+=1
)
```

Simultaneous pubkeys calculation will overly complicate the program.
And important: for N keys, performance will drop N times.
Sry, but i dont do it.
