### ISSUE TITLE
calculation error

### ISSUE THREAD

**Issue by dem10** [Telariust/pollard-kangaroo#4]
It seems to me or the program does not find the key? Starting out of the box, key (32) b862a62e
results.txt
00000000000000000000000000000000000000000000000000000000d33fcec3
---------------
000000000000000000000000000000000000000000000000000000008dc18338
---------------
00000000000000000000000000000000000000000000000000000000aab8fd4e
---------------
00000000000000000000000000000000000000000000000000000000cec01576
---------------
000000000000000000000000000000000000000000000000000000009740dc07
---------------
00000000000000000000000000000000000000000000000000000000f561490f
---------------
0000000000000000000000000000000000000000000000000000000092619f55
---------------
00000000000000000000000000000000000000000000000000000000e495df08
---------------
00000000000000000000000000000000000000000000000000000000a4490afb
---------------
00000000000000000000000000000000000000000000000000000000820f5707
---------------

**Comment by SatoshiNakamotoBitcoins** [comment]
@dem10 @Telariust To me also not (regarding 32 bit here as an example)

00000000000000000000000000000000000000000000000000000000fd9d3da6
---------------
00000000000000000000000000000000000000000000000000000000ac117641
---------------
00000000000000000000000000000000000000000000000000000000f13b3fe2
---------------
000000000000000000000000000000000000000000000000000000008cc3ffb7
---------------
00000000000000000000000000000000000000000000000000000000812b4da6
---------------
000000000000000000000000000000000000000000000000000000008008b07f
---------------
00000000000000000000000000000000000000000000000000000000bbe5e991
---------------
0000000000000000000000000000000000000000000000000000000093ef0f4e
---------------
00000000000000000000000000000000000000000000000000000000bf1b0498
---------------
000000000000000000000000000000000000000000000000000000008000b942
---------------

**Comment by Telariust** [comment]
I take out my magic ball and ask him what parameters you used?
..but a useless piece of glass stubbornly silent.
then i check
for privkey 00000000000000000000000000000000000000000000000000000000d33fcec3 
public key is 03b51474f995c573864e16ffd6424edba9c6310e1375867b4537d2b79aeb14371e
and run
```
>C:\Python37\python.exe 0_kangaroo_57fe.py 32 03b51474f995c573864e16ffd6424edba9c6310e1375867b4537d2b79aeb14371e
[################################################]
[# ECDSA Pollard-kangaroo PrivKey Recovery Tool #]
[#          based on code by 57fe 2019          #]
[#                  singlecore                  #]
[#                    ver 0.8                   #]
[################################################]
[date] Fri Sep 13 23:01:33 2019
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[PRNGseed] 842324014
[library#] gmpy2 (full speed available)
[profile#] optimal
[range] 2^31..2^32 ; W = U - L = 0x80000000 (2^31)
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[+] Sp-table of pow2 points - ready
[~~~~~~~~~~~~~~~~~~~~~~[1/1]~~~~~~~~~~~~~~~~~~~~~]
[i] custom pubkey#32 loaded from argv2
[pubkey#32] 03b51474f995c573864e16ffd6424edba9c6310e1375867b4537d2b79aeb14371e
[format] compressed
[Xcoordinate] b51474f995c573864e16ffd6424edba9c6310e1375867b4537d2b79aeb14371e
[Ycoordinate] 38e9cf73c50eaf36d15b5a4665f03645c2372a704e55daf025efc3b0fde44aed
[+] T1+W1 herds - ready

[prvkey#32] 0x00000000000000000000000000000000000000000000000000000000d33fcec3
[i] [2^31.0|---------------------------------------K--------------------|2^32.0]
[i] 78.9K j/s; 71.2Kj of 92.7Kj 76.8%; DP T1+W1=3+3=6; dp/kgr=3.0
[runtime]  0d 00:00:00s
[################################################]
[################################################]
[date] Fri Sep 13 23:01:34 2019
[################################################]

Press ENTER to get [prognose] or Ctrl+C to [exit] ...
```
wow, privkey found

**Comment by SatoshiNakamotoBitcoins** [comment]
@Telariust Thanks for your reply; so we have to add the desired bits keyspace and pubkey after the command script. Maybe you can add this in the text of the repo...how to use it...

Cheers Satoshi
