### ISSUE TITLE
wrong calc

### ISSUE THREAD

**Issue by hamnaz** [Telariust/pollard-kangaroo#5]
python3 kang2.py 10A3D70A3D70A3D70A3D70A3D6F:1147AE147AE147AE147AE147AE3 03bcf7ce887ffca5e62c9cabbdb7ffa71dc183c52c04ff4ee5ee82e0c55c39d77b
[################################################]
[# ECDSA Pollard-kangaroo PrivKey Recovery Tool #]
[#          based on code by 57fe 2019          #]
[#                  singlecore                  #]
[#                    ver 0.8                   #]
[################################################]
[date] Sat Sep 14 11:50:48 2019
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[PRNGseed] 2561502525
[library#] gmpy2 (full speed available)
[profile#] optimal
[range] 0x10a3d70a3d70a3d70a3d70a3d6f..0x1147ae147ae147ae147ae147ae3 ; W = U - L = 0xa3d70a3d70a3d70a3d70a3d74 (~2^100)
[warn!] W = 2^100 too big! long runtime expected
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[+] Sp-table of pow2 points - ready
[~~~~~~~~~~~~~~~~~~~~~~[1/1]~~~~~~~~~~~~~~~~~~~~~]
[i] custom pubkey#105 loaded from argv2
[pubkey#xx] 03bcf7ce887ffca5e62c9cabbdb7ffa71dc183c52c04ff4ee5ee82e0c55c39d77b
[format] compressed
[Xcoordinate] bcf7ce887ffca5e62c9cabbdb7ffa71dc183c52c04ff4ee5ee82e0c55c39d77b
[Ycoordinate] 0506c02f3b5c15c12deb94ba16d02bd9710eeaf3b25adf89cc5012ed9c44c31f
[+] T1+W1 herds - ready
[~] 223.9K j/s; 108.4Mj 0.0%; dp/kgr=0.0; [  0d 00:08:04s lost_TIME_left 15d 21:11:56s ]

this is some part or 105
above screen tells calc were 2 ^ 100

**Comment by hamnaz** [comment]
calc wrong 
[range] 0x10a3d70a3d70a3d70a3d70a3d6f..0x1147ae147ae147ae147ae147ae3 ; W = U - L = 0xa3d70a3d70a3d70a3d70a3d74 (~2^100)
[warn!] W = 2^100 too big! long runtime expected

actual start and end range is 105 bit

**Comment by Telariust** [comment]
```
0x00000000000000000000000000000000000001147AE147AE147AE147AE147AE3
-
0x000000000000000000000000000000000000010A3D70A3D70A3D70A3D70A3D6F
=
0x000000000000000000000000000000000000000a3d70a3d70a3d70a3d70a3d74
```
and its ~2^100

W is size of range
if you specify argv1 as bits, then W=2^(bits-1)
if you specify argv1 as L:U range, then W=U-L
size of W affects runtime of calculation

actual start and end range of 105 bit is
2^104..2^105
```
0x0000000000000000000000000000000000000100000000000000000000000000
0x0000000000000000000000000000000000000200000000000000000000000000
```
100000000000000000000000000:200000000000000000000000000

Note that TIME_left truncates time.
```
			if timeleft > 0:
				printstr += '%s ]  ' % ( time_format(timeleft, (1,1,1,1,1,1,0,0)) )
```
[warn!] W = 2^100 too big! long runtime expected
lost_TIME_left    726y  9m 27d 01:45:03s
..this really needs to be redone so as not to create an illusion
fixed in ver0.82
