### ISSUE TITLE
Error pollard-kangaroo-multi.py

### ISSUE THREAD

**Issue by dem10** [Telariust/pollard-kangaroo#7]
python 2.7 error(on python 3.7 it works)
Traceback (most recent call last):
  File "pollard-kangaroo-multi.py", line 567, in <module>
    mp.set_start_method('spawn')
AttributeError: 'module' object has no attribute 'set_start_method'

**Comment by kenni4** [comment]
copy gmpy2, kangaroo.py  python folder
dowloads install gmpy2
Python27>python -m pip install gmpy2-2.0.8-cp27-cp27m-win_amd64.whl 
Python37>python -m pip install gmpy2-2.0.8-cp37-cp37m-win_amd64.whl

Examle: windows command
cd Python37
python pollard-kangaroo-multi.py -h

![py3](https://user-images.githubusercontent.com/54586506/65636588-dde6bc80-dfe2-11e9-975a-2ba6c082ebda.PNG)

**Comment by Telariust** [comment]
thx, fixed python2 compatibility in 1.02
